//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int Id { get; set; }
        public string nom { get; set; }
        public Nullable<int> idelement { get; set; }
        public Nullable<int> idchoix { get; set; }
        public Nullable<int> ordre { get; set; }
        public string format { get; set; }
        public Nullable<int> position { get; set; }
    
        public virtual Elements Elements { get; set; }
    }
}
