//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponses
    {
        public int Id { get; set; }
        public Nullable<int> idElement { get; set; }
        public string intitueleElement { get; set; }
        public Nullable<bool> statut { get; set; }
        public Nullable<int> idResultat { get; set; }
        public string texteQuestion { get; set; }
    
        public virtual Resultat Resultat { get; set; }
    }
}
