//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resultat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resultat()
        {
            this.Reponses = new HashSet<Reponses>();
        }
    
        public int Id { get; set; }
        public string intituleQuestionnaire { get; set; }
        public Nullable<int> idQuestionnaire { get; set; }
        public Nullable<int> idUtilisateur { get; set; }
        public Nullable<int> tempsPassage { get; set; }
        public Nullable<System.DateTime> datePassage { get; set; }
        public Nullable<double> noteObtenue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reponses> Reponses { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
